[package]
name = "ulysses"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substring = "1.4.5"

[[bin]]
name = "ulysses"
path = "ulysses.rs"
